import { ImageResponse } from '@vercel/og';
import { NextRequest } from 'next/server';

export const runtime = 'edge';

// Pretendard Bold 폰트 바이너리 로드
const fontPromise = fetch(
  'https://cdn.jsdelivr.net/gh/orioncactus/pretendard/packages/pretendard/dist/web/static/woff/Pretendard-Bold.woff'
).then((res) => {
  if (!res.ok) {
    throw new Error(`Failed to fetch font: ${res.statusText}`);
  }
  return res.arrayBuffer();
});

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    const title = searchParams.get('title') || 'Default Title';
    const tag = searchParams.get('tag') || 'Next.js';

    // 폰트 바이너리를 ArrayBuffer로 획득
    const fontData = await fontPromise;

    return new ImageResponse(
      (
        <div
          style={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            backgroundColor: '#0f172a',
            backgroundImage:
              'radial-gradient(circle at 25px 25px, rgba(255, 255, 255, 0.05) 2%, transparent 0%), radial-gradient(circle at 75px 75px, rgba(255, 255, 255, 0.05) 2%, transparent 0%)',
            backgroundSize: '100px 100px',
            padding: '60px 80px',
            fontFamily: '"Pretendard", sans-serif',
          }}
        >
          {/* 상단 태그 */}
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                backgroundColor: 'rgba(37, 99, 235, 0.15)',
                border: '1px solid rgba(59, 130, 246, 0.4)',
                color: '#60a5fa',
                padding: '8px 24px',
                borderRadius: '9999px',
                fontSize: 22,
                fontWeight: 700,
                letterSpacing: '0.05em',
                textTransform: 'uppercase',
                wordBreak: 'keep-all',
              }}
            >
              {tag}
            </div>
          </div>

          {/* 중앙 타이틀 (한글 단어 단위 개행 keep-all 적용) */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              flex: 1,
              padding: '24px 0',
            }}
          >
            <h1
              style={{
                fontSize: 64,
                fontWeight: 700,
                color: '#f8fafc',
                lineHeight: 1.3,
                margin: 0,
                letterSpacing: '-0.02em',
                wordBreak: 'keep-all',
                display: '-webkit-box',
                WebkitLineClamp: 3,
                WebkitBoxOrient: 'vertical',
                overflow: 'hidden',
              }}
            >
              {title}
            </h1>
          </div>

          {/* 하단 워터마크 */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              borderTop: '1px solid rgba(255, 255, 255, 0.1)',
              paddingTop: '24px',
            }}
          >
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                color: '#94a3b8',
                fontSize: 20,
                fontWeight: 700,
                gap: '10px',
              }}
            >
              <div
                style={{
                  width: 10,
                  height: 10,
                  borderRadius: '50%',
                  backgroundColor: '#38bdf8',
                }}
              />
              <span>Generated by OG-Maker</span>
            </div>
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
        headers: {
          'Cache-Control': 'public, max-age=31536000, immutable',
        },
        fonts: [
          {
            name: 'Pretendard',
            data: fontData,
            style: 'normal',
            weight: 700,
          },
        ],
      }
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(`Failed to generate the image: ${message}`, {
      status: 500,
    });
  }
}
