"use client";

import { ThemeId } from "@/types";

interface CardCanvasProps {
  theme: ThemeId;
  title: string;
  tag: string;
  description?: string;
  isDemoMode: boolean;
}

export function CardCanvas({
  theme,
  title,
  tag,
  description,
  isDemoMode,
}: CardCanvasProps) {
  const effectiveTitle = title.trim() || "Your Dynamic Title Goes Here";
  const effectiveTag = tag.trim() || "ARTICLE";

  switch (theme) {
    // 1. GRADIENT (PRO)
    case "gradient":
      return (
        <div className="w-full h-full bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-600 text-white p-6 sm:p-10 flex flex-col justify-between select-none relative overflow-hidden">
          {/* Top Tag */}
          <div className="flex items-center">
            <span className="inline-flex items-center bg-white/20 border border-white/35 text-white font-bold px-3.5 py-1 rounded-full text-[11px] sm:text-xs tracking-wider uppercase backdrop-blur-sm shadow-sm">
              {effectiveTag}
            </span>
          </div>

          {/* Center Title */}
          <div className="flex flex-col justify-center my-auto py-2">
            <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-white leading-snug line-clamp-3">
              {effectiveTitle}
            </h1>
            {description && (
              <p className="mt-2 text-xs sm:text-sm text-white/85 font-medium line-clamp-2">
                {description}
              </p>
            )}
          </div>

          {/* Watermark */}
          {isDemoMode && (
            <div className="border-t border-white/25 pt-2.5 sm:pt-3 flex items-center justify-between text-[11px] sm:text-xs text-white/90 font-bold">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-white inline-block" />
                <span>Generated by TinyOG (PRO Theme Demo)</span>
              </div>
            </div>
          )}
        </div>
      );

    // 2. MINIMAL (FREE)
    case "minimal":
      return (
        <div className="w-full h-full bg-[#fafafa] text-[#0f172a] p-6 sm:p-10 flex flex-col justify-between border-[8px] sm:border-[12px] border-slate-100 select-none relative overflow-hidden">
          {/* Top Tag */}
          <div className="flex items-center">
            <span className="inline-flex items-center bg-slate-100 border border-slate-300 text-slate-900 font-bold px-3.5 py-1 rounded-full text-[11px] sm:text-xs tracking-wider uppercase">
              {effectiveTag}
            </span>
          </div>

          {/* Center Title */}
          <div className="flex flex-col justify-center my-auto py-2">
            <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-slate-900 leading-snug line-clamp-3">
              {effectiveTitle}
            </h1>
            {description && (
              <p className="mt-2 text-xs sm:text-sm text-slate-500 font-medium line-clamp-2">
                {description}
              </p>
            )}
          </div>

          {/* Watermark */}
          {isDemoMode && (
            <div className="border-t border-slate-200 pt-2.5 sm:pt-3 flex items-center justify-between text-[11px] sm:text-xs text-slate-500 font-bold">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-slate-900 inline-block" />
                <span>Generated by TinyOG</span>
              </div>
            </div>
          )}
        </div>
      );

    // 3. TERMINAL (PRO)
    case "terminal":
      return (
        <div className="w-full h-full bg-[#18181b] p-3 sm:p-5 flex flex-col justify-center select-none">
          <div className="w-full h-full bg-[#09090b] border border-[#27272a] rounded-lg sm:rounded-xl p-4 sm:p-6 flex flex-col justify-between">
            {/* Terminal Topbar */}
            <div className="flex items-center justify-between border-b border-[#27272a] pb-2.5 sm:pb-3">
              <div className="flex items-center gap-1.5 sm:gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-red-500 inline-block" />
                <span className="w-2.5 h-2.5 rounded-full bg-yellow-500 inline-block" />
                <span className="w-2.5 h-2.5 rounded-full bg-green-500 inline-block" />
              </div>
              <span className="inline-flex items-center bg-green-500/15 border border-green-500/30 text-green-400 font-mono font-bold px-2.5 py-0.5 rounded-full text-[10px] sm:text-xs tracking-wider uppercase">
                $ {effectiveTag}
              </span>
            </div>

            {/* Terminal Body */}
            <div className="flex items-start gap-2 sm:gap-3 my-auto py-2">
              <span className="text-green-400 font-mono font-bold text-base sm:text-2xl leading-none pt-0.5">
                ❯
              </span>
              <div className="flex-1">
                <h1 className="text-base sm:text-xl md:text-2xl font-bold font-mono text-zinc-100 leading-snug line-clamp-3">
                  {effectiveTitle}
                </h1>
                {description && (
                  <p className="mt-1.5 text-xs text-zinc-400 font-mono line-clamp-2">
                    # {description}
                  </p>
                )}
              </div>
            </div>

            {/* Terminal Footer */}
            {isDemoMode && (
              <div className="border-t border-[#27272a] pt-2 sm:pt-2.5 flex items-center text-[10px] sm:text-xs text-zinc-500 font-mono font-bold">
                <div className="flex items-center gap-1.5 sm:gap-2">
                  <span className="w-2 h-2 rounded-full bg-green-500 inline-block" />
                  <span>bash — Generated by TinyOG (PRO Theme Demo)</span>
                </div>
              </div>
            )}
          </div>
        </div>
      );

    // 4. NOTION (PRO)
    case "notion":
      return (
        <div className="w-full h-full bg-[#fbfbfa] text-[#37352f] p-6 sm:p-10 flex flex-col justify-between border-[8px] sm:border-[12px] border-[#f1f0eb] select-none relative overflow-hidden font-sans">
          {/* Top Tag */}
          <div className="flex items-center">
            <span className="inline-flex items-center gap-1.5 bg-[#f1f1ef] border border-[#e3e2de] text-[#37352f] font-semibold px-2.5 py-1 rounded text-[11px] sm:text-xs tracking-wide uppercase">
              <span className="w-2 h-2 rounded-[2px] bg-[#787774] inline-block" />
              <span>{effectiveTag}</span>
            </span>
          </div>

          {/* Center Title */}
          <div className="flex flex-col justify-center my-auto py-2">
            <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-[#37352f] leading-snug line-clamp-3">
              {effectiveTitle}
            </h1>
            {description && (
              <p className="mt-2 text-xs sm:text-sm text-[#787774] font-medium line-clamp-2">
                {description}
              </p>
            )}
          </div>

          {/* Watermark */}
          {isDemoMode && (
            <div className="border-t border-[#e3e2de] pt-2.5 sm:pt-3 flex items-center justify-between text-[11px] sm:text-xs text-[#787774] font-medium">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-[2px] bg-[#37352f] inline-block" />
                <span>Generated by TinyOG (PRO Theme Demo)</span>
              </div>
            </div>
          )}
        </div>
      );

    // 5. BENTO (PRO)
    case "bento":
      return (
        <div className="w-full h-full bg-[#09090b] p-3 sm:p-5 flex flex-col justify-center select-none relative overflow-hidden">
          {/* Radial Subtle Glow */}
          <div className="absolute -top-16 -right-16 w-48 h-48 bg-indigo-500/20 rounded-full blur-3xl pointer-events-none" />
          <div className="absolute -bottom-16 -left-16 w-48 h-48 bg-purple-500/15 rounded-full blur-3xl pointer-events-none" />

          {/* Bento Card */}
          <div className="relative w-full h-full bg-white/[0.03] border border-white/[0.09] rounded-xl sm:rounded-2xl p-5 sm:p-8 flex flex-col justify-between backdrop-blur-md">
            {/* Top Tag */}
            <div className="flex items-center">
              <span className="inline-flex items-center gap-1.5 bg-white/[0.06] border border-white/[0.14] text-zinc-200 font-bold px-3 py-1 rounded-full text-[11px] sm:text-xs tracking-wider uppercase">
                <span className="w-2 h-2 rounded-full bg-indigo-400 inline-block" />
                <span>{effectiveTag}</span>
              </span>
            </div>

            {/* Center Title */}
            <div className="flex flex-col justify-center my-auto py-2">
              <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-white leading-snug line-clamp-3">
                {effectiveTitle}
              </h1>
              {description && (
                <p className="mt-2 text-xs sm:text-sm text-zinc-400 font-medium line-clamp-2">
                  {description}
                </p>
              )}
            </div>

            {/* Watermark */}
            {isDemoMode && (
              <div className="border-t border-white/[0.08] pt-2.5 sm:pt-3 flex items-center justify-between text-[11px] sm:text-xs text-zinc-400 font-bold">
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-indigo-400 inline-block" />
                  <span>Generated by TinyOG (PRO Theme Demo)</span>
                </div>
              </div>
            )}
          </div>
        </div>
      );

    // 6. CYBERPUNK (PRO)
    case "cyberpunk":
      return (
        <div className="w-full h-full bg-[#07020d] text-white p-5 sm:p-9 flex flex-col justify-between border-4 sm:border-6 border-[#00f2fe] select-none relative overflow-hidden">
          {/* Neon Radial Glows */}
          <div className="absolute top-0 right-0 w-48 h-48 bg-[#00f2fe]/15 rounded-full blur-3xl pointer-events-none" />
          <div className="absolute bottom-0 left-0 w-48 h-48 bg-[#fe019a]/15 rounded-full blur-3xl pointer-events-none" />

          {/* Top Tag */}
          <div className="relative flex items-center z-10">
            <span className="inline-flex items-center gap-1.5 bg-[#00f2fe]/10 border border-[#00f2fe] text-[#00f2fe] font-mono font-bold px-2.5 py-0.5 rounded text-[11px] sm:text-xs tracking-widest uppercase">
              <span className="w-2 h-2 bg-[#fe019a] inline-block" />
              <span>// {effectiveTag}</span>
            </span>
          </div>

          {/* Center Title */}
          <div className="relative flex flex-col justify-center my-auto py-2 z-10">
            <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-white leading-snug line-clamp-3 drop-shadow-[0_0_12px_rgba(0,242,254,0.35)]">
              {effectiveTitle}
            </h1>
            {description && (
              <p className="mt-2 text-xs sm:text-sm text-[#fe019a] font-semibold line-clamp-2 font-mono">
                {description}
              </p>
            )}
          </div>

          {/* Watermark */}
          {isDemoMode && (
            <div className="relative border-t border-[#00f2fe]/30 pt-2.5 sm:pt-3 flex items-center justify-between text-[10px] sm:text-xs text-[#00f2fe] font-mono font-bold z-10">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 bg-[#fe019a] inline-block" />
                <span>SYSTEM // Generated by TinyOG (PRO Theme Demo)</span>
              </div>
            </div>
          )}
        </div>
      );

    // 7. SUNSET (PRO)
    case "sunset":
      return (
        <div className="w-full h-full bg-gradient-to-br from-amber-600 via-fuchsia-600 to-indigo-900 text-white p-6 sm:p-10 flex flex-col justify-between select-none relative overflow-hidden">
          {/* Top Tag */}
          <div className="flex items-center">
            <span className="inline-flex items-center gap-1.5 bg-white/20 border border-white/40 text-white font-bold px-3.5 py-1 rounded-full text-[11px] sm:text-xs tracking-wider uppercase backdrop-blur-sm shadow-sm">
              <span className="w-2 h-2 rounded-full bg-amber-300 inline-block" />
              <span>{effectiveTag}</span>
            </span>
          </div>

          {/* Center Title */}
          <div className="flex flex-col justify-center my-auto py-2">
            <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-white leading-snug line-clamp-3">
              {effectiveTitle}
            </h1>
            {description && (
              <p className="mt-2 text-xs sm:text-sm text-white/90 font-medium line-clamp-2">
                {description}
              </p>
            )}
          </div>

          {/* Watermark */}
          {isDemoMode && (
            <div className="border-t border-white/25 pt-2.5 sm:pt-3 flex items-center justify-between text-[11px] sm:text-xs text-white/90 font-bold">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-amber-300 inline-block" />
                <span>Generated by TinyOG (PRO Theme Demo)</span>
              </div>
            </div>
          )}
        </div>
      );

    // 8. DARK (FREE - DEFAULT)
    case "dark":
    default:
      return (
        <div className="w-full h-full bg-[#0f172a] text-[#f8fafc] p-6 sm:p-10 flex flex-col justify-between select-none relative overflow-hidden">
          {/* Subtle Matrix Dot Grid Background */}
          <div
            className="absolute inset-0 opacity-20 pointer-events-none"
            style={{
              backgroundImage:
                "radial-gradient(circle at 15px 15px, rgba(255, 255, 255, 0.4) 1px, transparent 0)",
              backgroundSize: "30px 30px",
            }}
          />

          {/* Top Tag */}
          <div className="relative flex items-center z-10">
            <span className="inline-flex items-center bg-blue-500/15 border border-blue-500/40 text-blue-400 font-bold px-3.5 py-1 rounded-full text-[11px] sm:text-xs tracking-wider uppercase">
              {effectiveTag}
            </span>
          </div>

          {/* Center Title */}
          <div className="relative flex flex-col justify-center my-auto py-2 z-10">
            <h1 className="text-lg sm:text-2xl md:text-3xl font-bold tracking-tight text-slate-50 leading-snug line-clamp-3">
              {effectiveTitle}
            </h1>
            {description && (
              <p className="mt-2 text-xs sm:text-sm text-slate-400 font-medium line-clamp-2">
                {description}
              </p>
            )}
          </div>

          {/* Watermark */}
          {isDemoMode && (
            <div className="relative border-t border-white/10 pt-2.5 sm:pt-3 flex items-center justify-between text-[11px] sm:text-xs text-slate-400 font-bold z-10">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-sky-400 inline-block" />
                <span>Generated by TinyOG</span>
              </div>
            </div>
          )}
        </div>
      );
  }
}
