import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — TinyOG",
  description: "Terms of Service for TinyOG - Dynamic Open Graph Image Generator at tinyog.cloud",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#09090b] text-[#f4f4f5] flex flex-col items-center justify-start p-6 md:p-12 font-sans selection:bg-zinc-800 selection:text-zinc-100">
      <div className="w-full max-w-3xl flex flex-col gap-8">
        {/* Navigation */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-xs font-mono text-zinc-400 hover:text-white transition-colors w-fit"
        >
          <svg
            className="w-3.5 h-3.5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M10 19l-7-7m0 0l7-7m-7 7h18"
            />
          </svg>
          Back to TinyOG
        </Link>

        {/* Header */}
        <header className="border-b border-[#27272a] pb-6">
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded bg-zinc-900 border border-zinc-800 text-zinc-400 text-[11px] font-mono uppercase tracking-wider mb-3">
            Legal &amp; Compliance
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-[#fafafa]">
            Terms of Service
          </h1>
          <p className="text-xs text-zinc-500 font-mono mt-2">
            Last updated: September 7, 2026 • Official Domain:{" "}
            <a
              href="https://tinyog.cloud"
              className="text-zinc-300 hover:underline"
            >
              https://tinyog.cloud
            </a>
          </p>
        </header>

        {/* Content */}
        <div className="flex flex-col gap-6 text-zinc-400 text-sm leading-relaxed">
          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">1. Acceptance of Terms</h2>
            <p>
              By accessing, browsing, or using TinyOG hosted at{" "}
              <a
                href="https://tinyog.cloud"
                className="text-zinc-200 hover:underline font-medium"
              >
                https://tinyog.cloud
              </a>{" "}
              (&quot;the Service&quot;), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must discontinue use of the Service immediately.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">2. Description of Service</h2>
            <p>
              TinyOG is an automated, edge-rendered Open Graph image generation platform operated at{" "}
              <code className="text-zinc-300 font-mono text-xs bg-zinc-900 px-1.5 py-0.5 rounded border border-zinc-800">https://tinyog.cloud</code> that allows users to produce dynamic social share cards and thumbnails using URL parameters and web interfaces.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">3. Licenses and Purchases</h2>
            <p>
              <strong className="text-zinc-200">Free Tier:</strong> Allows non-commercial and commercial generation of Open Graph images with standard themes and a mandatory &quot;Generated by TinyOG&quot; watermark.
            </p>
            <p>
              <strong className="text-zinc-200">Lifetime Pass (PRO):</strong> Purchased through Lemon Squeezy (our Merchant of Record). A valid license key grants a perpetual, non-exclusive license to remove watermarks and access all premium themes (e.g., Gradient, Terminal). License keys are non-transferable and may not be publicly shared or redistributed.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">4. User Content &amp; Intellectual Property</h2>
            <p>
              You retain all ownership and copyright rights to the text, titles, and parameters you input into TinyOG. You are solely responsible for ensuring your text content does not infringe upon any third-party trademark or copyright.
            </p>
            <p>
              TinyOG retains all rights, title, and interest in and to the Service, including its code, software architecture, UI design, logos, and trademarks.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">5. Prohibited Uses</h2>
            <p>
              You agree not to misuse TinyOG, including but not limited to:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-zinc-400">
              <li>Generating harmful, abusive, defamatory, or illegal content.</li>
              <li>Attempting to reverse-engineer, decompile, or bypass the license key verification mechanisms.</li>
              <li>Launching denial-of-service (DoS) attacks or intentionally degrading edge server performance.</li>
            </ul>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">6. Disclaimer &amp; Limitation of Liability</h2>
            <p>
              TinyOG is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without warranties of any kind, whether express or implied. Under no circumstances shall TinyOG, its operators, or affiliates be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the Service.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-zinc-100">7. Changes to Terms</h2>
            <p>
              We reserve the right to revise or modify these Terms of Service at any time. Changes will be posted to this page with an updated &quot;Last updated&quot; date. Continued use of TinyOG after changes are published constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="flex flex-col gap-2 border-t border-[#27272a] pt-6">
            <h2 className="text-base font-bold text-zinc-100">8. Contact Information</h2>
            <p>
              For legal inquiries, licensing questions, or support regarding these Terms, please contact us at:{" "}
              <a
                href="mailto:support@tinyog.cloud"
                className="text-zinc-200 hover:text-white underline font-medium"
              >
                support@tinyog.cloud
              </a>
            </p>
          </section>
        </div>

        {/* Footer info */}
        <footer className="mt-8 pt-6 border-t border-[#27272a] text-xs text-zinc-500 font-mono flex items-center justify-between">
          <span>© 2026 TinyOG (tinyog.cloud). All rights reserved.</span>
          <Link href="/" className="text-zinc-400 hover:text-white transition-colors">
            Return to Generator
          </Link>
        </footer>
      </div>
    </main>
  );
}
