import { OgThemeProps } from '../types';

export function BentoTheme({ title, tag, description, isPro }: OgThemeProps) {
  return (
    <div
      style={{
        height: '100%',
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        backgroundColor: '#09090b',
        backgroundImage:
          'radial-gradient(circle at 90% 10%, rgba(99, 102, 241, 0.15) 0%, transparent 45%), radial-gradient(circle at 10% 90%, rgba(168, 85, 247, 0.12) 0%, transparent 45%)',
        padding: '40px 50px',
        fontFamily: '"Pretendard", sans-serif',
      }}
    >
      {/* Bento Inner Glass Card */}
      <div
        style={{
          height: '100%',
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          backgroundColor: 'rgba(255, 255, 255, 0.03)',
          borderRadius: '24px',
          border: '1px solid rgba(255, 255, 255, 0.09)',
          padding: '40px 50px',
        }}
      >
        {/* 상단 태그 */}
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              backgroundColor: 'rgba(255, 255, 255, 0.06)',
              border: '1px solid rgba(255, 255, 255, 0.14)',
              color: '#e4e4e7',
              padding: '8px 22px',
              borderRadius: '9999px',
              fontSize: 20,
              fontWeight: 700,
              letterSpacing: '0.05em',
              textTransform: 'uppercase',
              wordBreak: 'keep-all',
              gap: '8px',
            }}
          >
            <div
              style={{
                width: 8,
                height: 8,
                borderRadius: '50%',
                backgroundColor: '#818cf8',
              }}
            />
            <span>{tag}</span>
          </div>
        </div>

        {/* 중앙 타이틀 & 설명 */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            flex: 1,
            padding: '24px 0',
          }}
        >
          <h1
            style={{
              fontSize: description ? 52 : 62,
              fontWeight: 700,
              color: '#fafafa',
              lineHeight: 1.25,
              margin: 0,
              letterSpacing: '-0.02em',
              wordBreak: 'keep-all',
              display: '-webkit-box',
              WebkitLineClamp: description ? 2 : 3,
              WebkitBoxOrient: 'vertical',
              overflow: 'hidden',
            }}
          >
            {title}
          </h1>
          {description ? (
            <p
              style={{
                fontSize: 26,
                fontWeight: 500,
                color: '#a1a1aa',
                lineHeight: 1.4,
                margin: '16px 0 0 0',
                wordBreak: 'keep-all',
                display: '-webkit-box',
                WebkitLineClamp: 2,
                WebkitBoxOrient: 'vertical',
                overflow: 'hidden',
              }}
            >
              {description}
            </p>
          ) : null}
        </div>

        {/* 하단 워터마크 (isPro가 false일 때만 노출) */}
        {!isPro && (
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              borderTop: '1px solid rgba(255, 255, 255, 0.08)',
              paddingTop: '20px',
            }}
          >
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                color: '#71717a',
                fontSize: 18,
                fontWeight: 700,
                gap: '10px',
              }}
            >
              <div
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: '50%',
                  backgroundColor: '#818cf8',
                }}
              />
              <span>Generated by TinyOG (PRO Theme Demo)</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
