import { OgThemeProps } from '../types';

export function GradientTheme({ title, tag, description, isPro }: OgThemeProps) {
  return (
    <div
      style={{
        height: '100%',
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        backgroundImage:
          'linear-gradient(135deg, #4f46e5 0%, #7c3aed 50%, #db2777 100%)',
        padding: '60px 80px',
        fontFamily: '"Pretendard", sans-serif',
      }}
    >
      {/* 상단 태그 */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            border: '1px solid rgba(255, 255, 255, 0.35)',
            color: '#ffffff',
            padding: '8px 24px',
            borderRadius: '9999px',
            fontSize: 22,
            fontWeight: 700,
            letterSpacing: '0.05em',
            textTransform: 'uppercase',
            wordBreak: 'keep-all',
          }}
        >
          {tag}
        </div>
      </div>

      {/* 중앙 타이틀 & 설명 */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          flex: 1,
          padding: '24px 0',
        }}
      >
        <h1
          style={{
            fontSize: description ? 54 : 64,
            fontWeight: 700,
            color: '#ffffff',
            lineHeight: 1.25,
            margin: 0,
            letterSpacing: '-0.02em',
            wordBreak: 'keep-all',
            display: '-webkit-box',
            WebkitLineClamp: description ? 2 : 3,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden',
          }}
        >
          {title}
        </h1>
        {description ? (
          <p
            style={{
              fontSize: 26,
              fontWeight: 500,
              color: 'rgba(255, 255, 255, 0.85)',
              lineHeight: 1.4,
              margin: '16px 0 0 0',
              wordBreak: 'keep-all',
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
              overflow: 'hidden',
            }}
          >
            {description}
          </p>
        ) : null}
      </div>

      {/* 하단 워터마크 (isPro가 false일 때만 노출) */}
      {!isPro && (
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            borderTop: '1px solid rgba(255, 255, 255, 0.25)',
            paddingTop: '24px',
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              color: 'rgba(255, 255, 255, 0.9)',
              fontSize: 20,
              fontWeight: 700,
              gap: '10px',
            }}
          >
            <div
              style={{
                width: 10,
                height: 10,
                borderRadius: '50%',
                backgroundColor: '#ffffff',
              }}
            />
            <span>Generated by TinyOG (PRO Theme Demo)</span>
          </div>
        </div>
      )}
    </div>
  );
}
