import { OgThemeProps } from '../types';

export function NotionTheme({ title, tag, description, isPro }: OgThemeProps) {
  return (
    <div
      style={{
        height: '100%',
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        backgroundColor: '#fbfbfa',
        padding: '60px 80px',
        border: '16px solid #f1f0eb',
        fontFamily: '"Pretendard", sans-serif',
      }}
    >
      {/* 상단 태그 */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            backgroundColor: '#f1f1ef',
            border: '1px solid #e3e2de',
            color: '#37352f',
            padding: '8px 22px',
            borderRadius: '6px',
            fontSize: 20,
            fontWeight: 700,
            letterSpacing: '0.04em',
            textTransform: 'uppercase',
            wordBreak: 'keep-all',
            gap: '8px',
          }}
        >
          <div
            style={{
              width: 8,
              height: 8,
              borderRadius: '2px',
              backgroundColor: '#787774',
            }}
          />
          <span>{tag}</span>
        </div>
      </div>

      {/* 중앙 타이틀 & 설명 */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          flex: 1,
          padding: '24px 0',
        }}
      >
        <h1
          style={{
            fontSize: description ? 54 : 64,
            fontWeight: 700,
            color: '#37352f',
            lineHeight: 1.25,
            margin: 0,
            letterSpacing: '-0.02em',
            wordBreak: 'keep-all',
            display: '-webkit-box',
            WebkitLineClamp: description ? 2 : 3,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden',
          }}
        >
          {title}
        </h1>
        {description ? (
          <p
            style={{
              fontSize: 26,
              fontWeight: 500,
              color: '#787774',
              lineHeight: 1.4,
              margin: '16px 0 0 0',
              wordBreak: 'keep-all',
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
              overflow: 'hidden',
            }}
          >
            {description}
          </p>
        ) : null}
      </div>

      {/* 하단 워터마크 (isPro가 false일 때만 노출) */}
      {!isPro && (
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            borderTop: '1px solid #e3e2de',
            paddingTop: '24px',
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              color: '#787774',
              fontSize: 20,
              fontWeight: 700,
              gap: '10px',
            }}
          >
            <div
              style={{
                width: 10,
                height: 10,
                borderRadius: '2px',
                backgroundColor: '#37352f',
              }}
            />
            <span>Generated by TinyOG (PRO Theme Demo)</span>
          </div>
        </div>
      )}
    </div>
  );
}
